# Commercial investigation vertical extraction

Load the **commercial_investigation** subset from intent-classified data, then extract **business verticals** (e.g. sports, health, real estate) using:
1. **IAB Content Taxonomy** keyword matching (all queries + all answers)
2. **LLM-based** structured output with intent re-classification (parallel, cached)
3. **Embedding-based** similarity to reference verticals
4. **Rule-based** vertical keywords (optional)

Uses **all user messages (all queries)** and **all assistant messages (all answers)** per conversation.

In [1]:
# Control variables (edit and run first)
INTENT_OUTPUT_DIR = "intent_output"
USE_SAMPLE = True
SAMPLE_N = 2000
RANDOM_SEED = 42
RUN_TAXONOMY = True
RUN_LLM_VERTICAL = True
RUN_EMBEDDING_VERTICAL = True
RUN_RULE_VERTICAL = True
IAB_DATA_DIR = None   # e.g. Path("data") to use data/iab_content_taxonomy_tier1_tier2.csv
VERTICAL_LLM_CACHE_PATH = "intent_output/vertical_intent_llm.parquet"
LLM_BATCH_SIZE = 150
LLM_MAX_WORKERS = 150  # set batch_size >= max_workers to use all workers; rate limits reported after run

## Load commercial_investigation and add text columns

Load the commercial_investigation parquet, ensure conversation is parsed, optionally sample, then add **all_queries** and **all_answers** (all user and all assistant messages per conversation).

In [2]:
from pathlib import Path
import pandas as pd

from eda_utils import ensure_conversation_parsed
from intent_analysis_utils import ensure_conversation_normalized
from intent_taxonomy import load_category
from commercial_vertical_utils import add_all_queries_answers_columns

df = load_category(INTENT_OUTPUT_DIR, "commercial_investigation", which="major")
df = ensure_conversation_parsed(df)
df = ensure_conversation_normalized(df)
if USE_SAMPLE and len(df) > SAMPLE_N:
    df = df.sample(n=min(SAMPLE_N, len(df)), random_state=RANDOM_SEED).reset_index(drop=True)
df = add_all_queries_answers_columns(df, conversation_col="conversation")
print(f"Loaded {len(df)} commercial_investigation rows. Columns: {list(df.columns)}")
df[["conversation_id", "all_queries", "all_answers"]].head(2)

Loaded 2000 commercial_investigation rows. Columns: ['conversation_id', 'model', 'timestamp', 'conversation', 'turn', 'language', 'openai_moderation', 'detoxify_moderation', 'toxic', 'redacted', 'text', 'intent_major', 'intent_sub', 'all_queries', 'all_answers']

,conversation_id,all_queries,all_answers
0,dd7456f94191d7684daf0309055c277d,create a humor immaculately detailed Scott the...,"I'm sorry, I cannot generate inappropriate or ..."
1,3e7bdb47db4b98df9d4d2fae1191eed0,If a female friend does wear a dress size 8. I...,It is difficult to accurately estimate someone...

## Taxonomy-based vertical (IAB keyword match)

Match keywords from **all_queries + all_answers** to IAB Content Taxonomy (Tier 1 / Tier 2). Uses local CSV in `data/` if `IAB_DATA_DIR` is set, otherwise fetches from IAB GitHub or uses embedded fallback.

In [3]:
if RUN_TAXONOMY:
    from commercial_vertical_utils import assign_vertical_iab

    data_dir = Path(IAB_DATA_DIR) if IAB_DATA_DIR else None
    df = assign_vertical_iab(
        df,
        text_col_queries="all_queries",
        text_col_answers="all_answers",
        data_dir=data_dir,
    )
    print("Vertical (IAB) Tier 1 value counts:")
    display(df["vertical_tier1_iab"].value_counts().head(15))

Vertical (IAB) Tier 1 value counts:

vertical_tier1_iab
Family and Relationships               684
Personal Celebrations & Life Events    277
Style & Fashion                        161
Sensitive Topics                       149
Home & Garden                          104
Hobbies & Interests                    103
Real Estate                             98
Food & Drink                            93
Sports                                  61
Healthy Living                          48
Education                               31
Medical Health                          25
Books and Literature                    24
Genres                                  21
Personal Finance                        21
Name: count, dtype: int64

## LLM-based vertical and intent re-classification

Call OpenAI with **all_queries + all_answers** per conversation; get structured JSON with `vertical_tier1`, `vertical_tier2`, and `intent_revised`. Runs in parallel with caching.

In [4]:
if RUN_LLM_VERTICAL:
    from dotenv import load_dotenv
    load_dotenv()

    from commercial_vertical_utils import label_vertical_intent_llm_parallel

    df = label_vertical_intent_llm_parallel(
        df,
        queries_col="all_queries",
        answers_col="all_answers",
        cache_path=VERTICAL_LLM_CACHE_PATH,
        use_cache=True,
        batch_size=LLM_BATCH_SIZE,
        max_workers=LLM_MAX_WORKERS,
    )
    print("Vertical (LLM) Tier 1 value counts:")
    display(df["vertical_tier1_llm"].value_counts().head(15))
    print("Intent revised vs intent_major:")
    display(pd.crosstab(df["intent_major"], df["intent_revised"], margins=True))

Vertical (LLM) Tier 1 value counts:

vertical_tier1_llm
Other            792
Technology       327
Education        323
Health           275
Sports            97
Travel            40
Shopping          34
Finance           34
Food & Drink      34
Automotive        11
Real Estate        8
Music              8
Art                3
Entertainment      3
Gaming             2
Name: count, dtype: int64

Intent revised vs intent_major:

intent_revised,commercial_investigation,informational,navigational,transactional,All
intent_major,,,,,
commercial_investigation,42,1939,10,9,2000
All,42,1939,10,9,2000

## Spot check: conversations by LLM vertical

Sample a few conversations for a **vertical of your choice** (LLM-assigned `vertical_tier1_llm`). Adjust `SPOTCHECK_VERTICAL` and `N_PER_VERTICAL` below, then run the cell.

In [5]:
# Spot check by vertical: pick a vertical and how many conversations to show
SPOTCHECK_VERTICAL = "Technology"   # change to any vertical_tier1_llm value (e.g. "Health", "Sports", "Other")
N_PER_VERTICAL = 3                 # number of conversations to print (adjustable)

if "vertical_tier1_llm" in df.columns:
    from intent_analysis_utils import sample_by_category, format_conversation
    available = sorted(df["vertical_tier1_llm"].dropna().unique().tolist())
    print(f"Available verticals: {available}\n")
    subset = df[df["vertical_tier1_llm"] == SPOTCHECK_VERTICAL]
    if len(subset) == 0:
        print(f"No rows with vertical_tier1_llm == {SPOTCHECK_VERTICAL!r}. Choose from: {available}")
    else:
        n = min(N_PER_VERTICAL, len(subset))
        sampled = subset.sample(n=n, random_state=RANDOM_SEED)
        print(f"Vertical: {SPOTCHECK_VERTICAL} (showing {n} of {len(subset)} conversations)\n")
        print("=" * 60)
        for idx, row in sampled.iterrows():
            print(f"--- conversation_id: {row['conversation_id']} ---")
            print(format_conversation(row["conversation"], width=80))
            print("=" * 60)
else:
    print("Run the LLM-based vertical cell first so vertical_tier1_llm exists.")

Available verticals: ['Art', 'Automotive', 'Beauty', 'Business', 'Economics', 'Education', 'Entertainment', 'Fashion', 'Finance', 'Food & Drink', 'Gaming', 'Health', 'Home', 'Home Improvement', 'Legal', 'Music', 'Other', 'Pets', 'Politics', 'Real Estate', 'Shopping', 'Sports', 'Technology', 'Travel']

Vertical: Technology (showing 3 of 327 conversations)

============================================================
--- conversation_id: d30e69ba51d3322ae58936b5b8d8895a ---
[user]
Hi there! Send best ideas for B2B startup

[assistant]
1. AI-powered lead generation platform: Develop an artificial intelligence (AI)
powered platform that identifies, scores, and matches prospective customers and
businesses with relevant products, services, or partners.  2. Virtual events and
webinars platform: Create a virtual event platform specifically designed for B2B
businesses enabling professionals to attend online workshops, webinars, and
conferences, as well as network and collaborate on various projects.  3. On-
demand B2B consulting services: Launch an online consulting marketplace catering
to B2B businesses, providing expert advice on various aspects like marketing,
sales, human resources, and more.  4. B2B E-commerce platform: Create a B2B
e-commerce platform where businesses can buy and sell products and services in
bulk at competitive prices.  5. Supply chain optimization and tracking software:
Develop a software solution that helps businesses analyze and optimize their
supply chain, streamline processes, and track shipments in real-time to reduce
costs and increase efficiency.  6. B2B mobile payment solutions: Offer a mobile
payment platform specifically designed for B2B transactions, making it easy for
businesses to send and receive payments.  7. B2B software subscription and usage
analytics: Create a software that monitors the usage and performance of various
cloud-based tools and software that businesses use, providing insights and
suggestions for optimization.  8. B2B cybersecurity services: Offer an end-to-
end cybersecurity solution for B2B organizations, providing vulnerability
assessment, risk management, and incident response services.  9. Green energy
solutions for businesses: Develop energy-efficient and sustainable solutions for
B2B businesses that can help them meet their energy goals and reduce their
carbon footprint.  10. B2B subscription box service: Create a subscription box
service for businesses, featuring office supplies, tech gadgets, and other
branded essentials, providing a convenient solution for businesses to stay
stocked up on necessary items.  11. Talent acquisition and onboarding platform:
Offer an AI-driven recruitment platform to help businesses find and hire the
best talent, as well as streamlining the onboarding process to improve employee
engagement and retention.  12. Collaboration and project management tools:
Design a cloud-based project management and collaboration tool that helps
distributed teams collaborate efficiently and track the progress of their
projects in real-time.  13. B2B customer feedback and review management
platform: Develop a platform that enables businesses to gather, analyze, and act
on customer feedback and online reviews more efficiently.  14. CRM (Customer
Relationship Management) software for niche industries: Build a CRM tool
tailored for specific industries, like manufacturing, healthcare, or real
estate, to help businesses manage their customer relationships more effectively.
15. B2B content marketing and analytics platform: Offer a platform that enables
businesses to plan, execute, and measure their marketing campaigns, providing
actionable insights to optimize their marketing strategy.
============================================================
--- conversation_id: 2459b8bf1cdff6e74dc1ac9f109bc1bd ---
[user]
Hi, I've implemented the given matlab code to classify emotions, age, and gender
of the subjects. The Face.mat dataset includes 12 images of 6 different
subjects. For each subjects we have 2 samples of 6 different emotions. Use one
of each samples in your training dataset and the other one in your testing
dataset. This way you would have 36 images in the training dataset and 36 images
in the testing dataset. Goal: To classify the gender (2 classes: M, F), emotions
(6 classes: angry, disgust, neutral, happy, sad, surprised) and age (3 classes:
Young, Mid age, Old). Using a linear classifier. You should label your training
and testing data for each of the classification problem separately. So, These
are the variables I'm gettting  the following error: >> project_4 Error using  *
Incorrect dimensions for matrix multiplication. Check that the number of columns
in the first matrix matches the number of rows in the second matrix. To operate
on each element of the matrix individually, use TIMES (.*) for elementwise
multiplication.  Error in project_4 (line 11) projTrainData = trainData' *
EigVec; The dataset contains the following : >> whos('-file', 'Face.mat')   Name
Size               Bytes  Class     Attributes    II        100820x72
58072320  double                 m              1x72                 576  double
. Afte running the code, The variables are defined as follows and this
information will help you find the root cause of the problem. As far as I know,
the testData and trainData sizes are mismatched. So, dig deeper , find the root
cause and fix the code. Variable      Size    Type EigVal  48x48   double EigVec
48x48   double II      100820x72       double m       1x72    double testData
100820x24       double testLabels      576x1   double trainData       100820x48
double trainLabels     2304x1  double Here is the code: % Load the dataset
load('Face.mat');  % Divide the dataset into training and testing [trainData,
testData, trainLabels, testLabels] = splitData(II, m);  % Calculate PCA on the
training dataset [EigVec, EigVal] = eig(cov(trainData));  % Project the images
onto the Eigenfaces projTrainData = trainData' * EigVec; projTestData =
testData' * EigVec;  % Select top 6 features using sequentialfs selection =
sequentialfs(@classifierEvalFunc, projTrainData, trainLabels);  % Train the
linear classifier using the selected features classifier =
fitcdiscr(projTrainData(:, selection), trainLabels);  % Test the classifier on
the testing data predictions = predict(classifier, projTestData(:, selection));
% Function to split the data into training and testing function [trainData,
testData, trainLabels, testLabels] = splitData(data, labels)
test_col_indices = 3:3:size(data, 2);     train_col_indices = 1:size(data, 2);
train_col_indices(test_col_indices) = [];          testData = data(:,
test_col_indices);     testLabels = labels(:, test_col_indices);
trainData = data(:, train_col_indices);     trainLabels = labels(:,
train_col_indices);          trainData = trainData(:);     trainData =
reshape(trainData, [size(data, 1), numel(train_col_indices)]);          testData
= testData(:);     testData = reshape(testData, [size(data, 1),
numel(test_col_indices)]);          testLabels = repmat(testLabels(:),
[numel(testLabels), 1]);          trainLabels = repmat(trainLabels(:),
[numel(trainLabels), 1]); end  % Function to evaluate the classifier for
sequentialfs function mse = classifierEvalFunc(X, y)     classifier =
fitcdiscr(X, y);     y_pred = predict(classifier, X);     mse = mean((y_pred -
y).^2);     end

[assistant]
As you mentioned, there seems to be an issue with the dimensions of the
`testData` and `trainData` variables. The problem comes from mismatched sizes of
testLabels and trainLabels, which are replicated using repmat instead of
resizing corresponding data. Let's fix this issue by modifying the function
`splitData`.  Replace your `splitData` function with this updated version:
```matlab function [trainData, testData, trainLabels, testLabels] =
splitData(data, labels)     test_col_indices = 3:3:size(data, 2);
train_col_indices = 1:size(data, 2);     train_col_indices(test_col_indices) =
[];          testData = data(:, test_col_indices);     testLabels = labels(:,
test_col_indices);          trainData = data(:, train_col_indices);
trainLabels = labels(:, train_col_indices);          trainData = trainData(:);
trainData = reshape(trainData, [size(data, 1), numel(train_col_indices)]);
testData = testData(:);     testData = reshape(testData, [size(data, 1),
numel(test_col_indices)]);          testLabels = testLabels(:);     trainLabels
= trainLabels(:); end ```  In the updated function, we have removed the
unnecessary lines of code that replicated `testLabels` and `trainLabels`. This
would ensure that the matrix dimensions are consistent, and the error should be
resolved.

[user]
I'm still getting the same error. Please dig a little bit deeper and carefully
find the root cause. All we are doing is splitting the data into train and test
sets and projecting those to get eigen faces. Once again push harder and fix the
issue once and for all. Here is the error:Error using  *  Incorrect dimensions
for matrix multiplication. Check that the number of columns in the first matrix
matches the number of rows in the second matrix. To operate on each element of
the matrix individually, use TIMES (.*) for elementwise multiplication.  Error
in project_4 (line 11) projTrainData = trainData' * EigVec;

[assistant]
Apologies for the confusion. Let's dig deeper into the code and find the root
cause of the error. It seems that the issue is related to incorrectly
calculating the Eigenvectors and Eigenvalues for the covariance matrix. To fix
this, we can modify the way we calculate the Eigenvectors by first normalizing
the training data, and then calculating the covariance matrix.  1. Subtract the
mean image from the training data and normalize it.  ```matlab meanTrainData =
mean(trainData, 2); normTrainData = trainData - meanTrainData; ```  2. Calculate
the Eigenvectors and Eigenvalues using the normalized training data.  ```matlab
[EigVec, EigVal] = eig(normTrainData' * normTrainData); ```  3. Update the code
for projecting the images onto the Eigenfaces using the normalized data.
```matlab projTrainData = normTrainData' * EigVec; projTestData = (testData -
meanTrainData)' * EigVec; ```  Here's the complete modified code with these
updates:  ```matlab % Load the dataset load('Face.mat');  % Divide the dataset
into training and testing [trainData, testData, trainLabels, testLabels] =
splitData(II, m);  % Subtract the mean image from the training data and
normalize it meanTrainData = mean(trainData, 2); normTrainData = trainData -
meanTrainData;  % Calculate PCA using normalized training dataset [EigVec,
EigVal] = eig(normTrainData' * normTrainData);  % Project the images onto the
Eigenfaces projTrainData = normTrainData' * EigVec; projTestData = (testData -
meanTrainData)' * EigVec;  % Select top 6 features using sequentialfs selection
= sequentialfs(@classifierEvalFunc, projTrainData, trainLabels);  % Train the
linear classifier using the selected features classifier =
fitcdiscr(projTrainData(:, selection), trainLabels);  % Test the classifier on
the testing data predictions = predict(classifier, projTestData(:, selection));
```  This modified code should resolve the error you were experiencing.

[user]
Implement the following Project Description: In this project you will use the
dataset Face.mat to classify emotions, age, and gender of the subjects. This
dataset includes 12 images of 6 different subjects. For each subjects we have 2
samples of 6 different emotions. Use one of each samples in your training
dataset and the other one in your testing dataset. This way you would have 36
images in the training dataset and 36 images in the testing dataset. Goal: To
classify the gender (2 classes: M, F), emotions (6 classes: angry, disgust,
neutral, happy, sad, surprised) and age (3 classes: Young, Mid age, Old). Using
a linear classifier. You should label your training and testing data for each of
the classification problem separately. Classifier: Develop and Use the linear
classifier Features: Projection of the image on each of the eigenfaces. For this
purpose, you need to calculate PCA of your training data. Your kth feature will
be the projection (dot product) of the image on the kth eigen vector (PCA
direction) also known as eigenface. Feature Selection: You will extract 36
Features as there are 36 images (and eigen vectors) in your training data. Use
the “sequentialfs” command in MATLAB to select the top 6 features using the
sequential forward search algorithm.

[assistant]
Here's an outline of the steps we need to implement according to the project
description:  1. Load the dataset. 2. Divide the dataset into training and
testing, 36 images each. 3. Calculate PCA on the training dataset. 4. Project
images onto Eigenfaces to get features. 5. Use sequentialfs to select the top 6
features. 6. Train and test a linear classifier using the selected features.
Here's the updated MATLAB code based on the project description with appropriate
labels:  ```matlab % Load the dataset load('Face.mat'); labels = [1 1 1 1 1 1 0
0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3
3 1 1 1 1 1 1 4 4 4 4 4 4 1 1 1 1 1 1 5 5 5 5 5 5]';  % Divide the dataset into
training and testing [trainData, testData, trainLabels, testLabels] =
splitData(II, labels);  % Normalize and compute PCA on the training dataset
meanTrainData = mean(trainData, 2); normTrainData = trainData - meanTrainData;
[EigVec, EigVal] = eig(normTrainData' * normTrainData);  % Project the images
onto the Eigenfaces projTrainData = normTrainData' * EigVec; projTestData =
(testData - meanTrainData)' * EigVec;  % Select top 6 features using
sequentialfs selection = sequentialfs(@classifierEvalFunc, projTrainData,
trainLabels);  % Train the linear classifier using the selected features
classifier = fitcdiscr(projTrainData(:, selection), trainLabels);  % Test the
classifier on the testing data predictions = predict(classifier, projTestData(:,
selection));  % Calculate accuracy accuracy = sum(predictions == testLabels) /
length(testLabels); disp(['Accuracy: ', num2str(accuracy * 100), '%']);  %
Function to split the data into training and testing function [trainData,
testData, trainLabels, testLabels] = splitData(data, labels)
test_col_indices = 3:3:size(data, 2);     train_col_indices = 1:size(data, 2);
train_col_indices(test_col_indices) = [];      testData = data(:,
test_col_indices);     testLabels = labels(:, test_col_indices);     trainData =
data(:, train_col_indices);     trainLabels = labels(:, train_col_indices);
trainData = trainData(:);     trainData = reshape(trainData, [size(data, 1),
numel(train_col_indices)]);     testData = testData(:);     testData =
reshape(testData, [size(data, 1), numel(test_col_indices)]);      testLabels =
testLabels(:);     trainLabels = trainLabels(:); end  % Function to evaluate the
classifier for sequentialfs function mse = classifierEvalFunc(X, y)
classifier = fitcdiscr(X, y);     y_pred = predict(classifier, X);     mse =
mean((y_pred - y).^2); end ```  In this code, we have added labels to classify
gender, emotion, and age of the subjects according to the project description.
The script trains and tests a linear classifier using the selected features and
calculates the accuracy of the classifier.  Please note that you will need to
modify the labels array based on the specific labeling for each subject's
gender, age, and emotion accordingly.

[user]
So, I've come with the following implementation since your's making me stuck
with the same error. But here I got one more error. Can you fix all the
loopholes and errors in the code. Note: The two variables in Face.mat are as
follows   Variable        Size    Data Type  Bytes  II      100820x72
double  50872320 m       1x72    double   576.      Error is>> project_4 Error
using  *  Incorrect dimensions for matrix multiplication. Check that the number
of columns in the first matrix matches the number of rows in the second matrix.
To operate on each element of the matrix individually, use TIMES (.*) for
elementwise multiplication.  Error in project_4 (line 46) projTrainData =
trainData' * EigVec; and the code is : % Load the dataset load('Face.mat');   %
Reshape the II matrix into a 72 x 1405 matrix II = reshape(II, [], size(m, 2));
% Separate the samples for training and testing trainData = zeros(size(II, 1),
36); testData = zeros(size(II, 1), 36); trainLabelsGender = zeros(1, 36);
testLabelsGender = zeros(1, 36); trainLabelsEmotions = zeros(1, 36);
testLabelsEmotions = zeros(1, 36); trainLabelsAge = zeros(1, 36); testLabelsAge
= zeros(1, 36);  for i = 1:6     % Use one sample of each emotion for training
and the other for testing     trainIndex = (i-1)*6+1;     testIndex = trainIndex
+ 1;          % Assign the samples to training and testing datasets
trainData(:, trainIndex) = II(:, trainIndex);     trainData(:, trainIndex+1) =
II(:, testIndex);     testData(:, testIndex) = II(:, testIndex);     testData(:,
testIndex-1) = II(:, trainIndex);          % Assign the gender labels
trainLabelsGender(trainIndex:trainIndex+1) = repmat(m(i), [1 2]);
testLabelsGender(testIndex-1:testIndex) = repmat(m(i), [1 2]);          % Assign
the emotion labels     trainLabelsEmotions(trainIndex:trainIndex+1) = [1 2];
testLabelsEmotions(testIndex-1:testIndex) = [1 2];          % Assign the age
labels     trainLabelsAge(trainIndex:trainIndex+1) = [i i];
testLabelsAge(testIndex-1:testIndex) = [i i]; end  % Calculate the PCA on the
training dataset [EigVec, EigVal] = eig(cov(trainData));  % Project the training
and testing data onto the Eigenfaces projTrainData = trainData' * EigVec;
projTestData = testData' * EigVec;  % Feature selection using sequential forward
search algorithm topFeaturesGender = sequentialfs(@linearClassifier,
projTrainData, trainLabelsGender, 'cv', 'none', 'nfeatures', 6);
topFeaturesEmotions = sequentialfs(@linearClassifier, projTrainData,
trainLabelsEmotions, 'cv', 'none', 'nfeatures', 6); topFeaturesAge =
sequentialfs(@linearClassifier, projTrainData, trainLabelsAge, 'cv', 'none',
'nfeatures', 6);  % Train the linear classifier for gender classification
trainDataGender = projTrainData(:, topFeaturesGender); testDataGender =
projTestData(:, topFeaturesGender); BGender = linearClassifier(trainDataGender,
trainLabelsGender); predictedLabelsGender = BGender(1) + testDataGender' *
BGender(2:end)'; predictedLabelsGender(predictedLabelsGender >= 0) = 1;
predictedLabelsGender(predictedLabelsGender < 0) = -1;  % Train the linear
classifier for emotion classification trainDataEmotions = projTrainData(:,
topFeaturesEmotions); testDataEmotions = projTestData(:, topFeaturesEmotions);
BEmotions = linearClassifier(trainDataEmotions, trainLabelsEmotions);
predictedLabelsEmotions = BEmotions(1) + testDataEmotions' * BEmotions(2:end)';
predictedLabelsEmotions = round(predictedLabelsEmotions);     % Train the linear
classifier for age classification trainDataAge = projTrainData(:,
topFeaturesAge); testDataAge = projTestData(:, topFeaturesAge); BAge =
linearClassifier(trainDataAge, trainLabelsAge); predictedLabelsAge = BAge(1) +
testDataAge' * BAge(2:end)'; predictedLabelsAge(predictedLabelsAge < 0) = 1;
predictedLabelsAge(predictedLabelsAge > 2) = 3;
predictedLabelsAge(predictedLabelsAge > 1 & predictedLabelsAge < 3) = 2;  %
Evaluate the classification results confusionMatrixGender =
confusionmat(testLabelsGender, predictedLabelsGender); accuracyGender =
sum(diag(confusionMatrixGender))/sum(confusionMatrixGender(:));
confusionMatrixEmotions = confusionmat(testLabelsEmotions,
predictedLabelsEmotions); accuracyEmotions =
sum(diag(confusionMatrixEmotions))/sum(confusionMatrixEmotions(:));
confusionMatrixAge = confusionmat(testLabelsAge, predictedLabelsAge);
accuracyAge = sum(diag(confusionMatrixAge))/sum(confusionMatrixAge(:));
fprintf('Accuracy for gender classification: %.2f%%\n', accuracyGender100);

## Spot check: re-classified intent by category

Sample a few conversations **per intent_revised** category to review how the LLM re-classified intent. Adjust `N_PER_INTENT` below, then run the cell.

In [6]:
# Spot check by intent_revised: how many conversations per intent category
N_PER_INTENT = 3   # number of conversations to print per intent_revised (adjustable)

if "intent_revised" in df.columns:
    from intent_analysis_utils import sample_by_category, format_conversation
    sampled = sample_by_category(
        df, category_col="intent_revised", n_per_cat=N_PER_INTENT, seed=RANDOM_SEED
    )
    for intent_cat in sampled["intent_revised"].dropna().unique():
        block = sampled[sampled["intent_revised"] == intent_cat]
        n_show = len(block)
        total = len(df[df["intent_revised"] == intent_cat])
        print(f"\n{'=' * 60}")
        print(f"intent_revised: {intent_cat} (showing {n_show} of {total})")
        print("=" * 60)
        for _, row in block.iterrows():
            print(f"--- conversation_id: {row['conversation_id']} | intent_major: {row['intent_major']} ---")
            print(format_conversation(row["conversation"], width=80))
            print("-" * 60)
else:
    print("Run the LLM-based vertical cell first so intent_revised exists.")

============================================================
intent_revised: commercial_investigation (showing 3 of 42)
============================================================
--- conversation_id: 517212b531203520b72f16a9f33dbfb2 | intent_major: commercial_investigation ---
[user]
{'Count': 5, 'title': 'バイクライフ-バイクと人生をより豊かに(AI Photobook)', 'englishtitle': 'Bike
Life - Make Your Life More Fulfilling with Bikes(AI Photobook)',
'katakanaoftitle': 'バイクライフ', '7ofdescriptionkeyword': ['バイク', '人生', '自由', '天空',
'旅行', '仲間', '冒険'], 'english7ofdescriptionkeyword': ['bike', 'life', 'freedom',
'sky', 'travel', 'comrades', 'adventure'], 'kdpofintroduction': 'もっと気楽に自由にバイクを楽し
んでみたいと思いませんか？バイクライフを送ることは、あなたの人生にも大きな影響を与えることでしょう。本書では、バイクに乗って自由な空間を訪れたり、仲間とともに旅
行に出かけたり、新しい冒険を始めたりする素晴らしいバイクライフスタイルをご紹介しています。', 'englishkdpofintroduction':
'Want to have more fun and freedom with your bike? Living the bike life can have
a profound impact on your life. This book features an array of thrilling bike
life experiences, from exploring open spaces on your bike, to taking trips with
friends, to embarking on new adventures.', 'prompt':
'<lora:japaneseDollLikeness_v15:0.3>(wearing the masterpiece:1.1),<lora:Euro-
AmericanDollLikeness_V20:0.6>,1 girl,(1 18-year-old girl),(upper
body),(realistic:1.7),((best quality)),absurdres,(ultra high
res),(photorealistic:1.6),photorealistic,octane render,(hyperrealistic:1.2),
(photorealistic face:1.2), (8k), (4k), (Masterpiece),(realistic skin texture),
(illustration, cinematic lighting,wallpaper),( beautiful eyes:1.2),((((perfect
face)))),(cute),(smile:0.9),(sitting on the bench),golden hair,(short hair),(bow
hairband),blue eyes,(red lips:1.1),,beautiful face,1girl,18yo,big breasts, solo,
(best quality), dynamic angle, full body, no helmet, looking at viewer,wearing
the leather jacket see through the bra:1.2, mini jeans, motorcycle boots, biker
bandanna, braided hair, relaxed posture', 'Negativeprompt': 'EasyNegative,
stills, food photography, (worst quality:2), (low quality:2), (normal
quality:2), lowres, normal quality, (full nudity), (only head), (only body),
(face obscured), unkempt
appearance'}最初の文に「著者ページ:https://www.amazon.co.jp/~/e/B0C5Y7H8CH 本リンク：https://www
.amazon.co.jp/dp/B0C74QYKR2」を書いた後、上記の内容をfacebookに宣伝するため、アピール投稿を英語で作ってください。

[assistant]
Author page: https://www.amazon.co.jp/~/e/B0C5Y7H8CH Book link:
https://www.amazon.co.jp/dp/B0C74QYKR2  ??️ Discover a whole new world of
freedom and adventure with "Bike Life - Make Your Life More Fulfilling with
Bikes (AI Photobook)"! ??️  Are you ready to live your life to the fullest on
your bike? Our AI Photobook is here to show you the incredible experiences you
can have when you embrace the bike life. Explore vast open spaces, embark on
thrilling road trips with friends, and dive into new adventures.  ?? Don't miss
this chance to transform your biking experience! Packed with gorgeous pictures
and content, this photo book will take you on the journey of a lifetime.  ??
Feat. a photorealistic and hyperrealistic masterpiece: an 18-year-old girl,
beautifully illustrated with a perfect face, cute smile, blue eyes, short golden
hair, sitting on a bench with a relaxed posture. Adorned in a leather jacket,
mini jeans, motorcycle boots, and biker bandanna – all in 4K & 8K ultra high-
resolution.  Grab your copy now and elevate your bike life today! ??️??
https://www.amazon.co.jp/dp/B0C74QYKR2
------------------------------------------------------------
--- conversation_id: 88430644a06d9cfa729fb63a1a9dc350 | intent_major: commercial_investigation ---
[user]
compare cb1300, suzuki gsx s1000, suzuki gsx  r 1000, yamaha r6, kawasaki z1000
, susuki b king, i want top speed, horsepower, and which one is hard or
dangerous to ride

[assistant]
Here is a comparison of the motorcycles you mentioned, focusing on top speed and
horsepower:  1. Honda CB1300    - Top Speed: 143 mph (230 km/h)     -
Horsepower: 114 hp    - Relatively easy and safe for experienced riders  2.
Suzuki GSX-S1000    - Top Speed: 155 mph (250 km/h)      - Horsepower: 150 hp
- Easy ride and safe for experienced riders  3. Suzuki GSX-R1000     - Top
Speed: 186 mph (299 km/h)    - Horsepower: 199 hp    - High-performance machine,
needs careful handling and an experienced rider  4. Yamaha R6    - Top Speed:
164 mph (262 km/h)    - Horsepower: 119 hp    - A sporty ride, best-suited for
experienced riders  5. Kawasaki Z1000    - Top Speed: 152 mph (245 km/h)    -
Horsepower: 142 hp    - A versatile bike that is suitable for beginners but
exciting for experienced riders  6. Suzuki B-King    - Top Speed: 155 mph (250
km/h)    - Horsepower: 181 hp    - A powerful ride that requires a bit more
experience to handle properly  In terms of top speed, the Suzuki GSX-R1000 is
the fastest with 186 mph (299 km/h), followed by the Yamaha R6 and Suzuki
B-King. The bike with the most horsepower is also the Suzuki GSX-R1000 with 199
hp.  As for being harder or more dangerous to ride, the Suzuki GSX-R1000, Yamaha
R6, and Suzuki B-King are all high-powered machines that require experienced
riders who can handle their performance capabilities. The remaining bikes, Honda
CB1300, Suzuki GSX-S1000, and Kawasaki Z1000 are more versatile, suitable for
beginners but still exciting for experienced riders. However, it is essential to
consider your riding experience, skills, and physical capabilities before
purchasing a high-performance motorcycle.

[user]
i heard is so dangerous to ride suzuki s1000, how do you think its good for
beginners? and also which one is good, z1000 or s1000 ?

[assistant]
Apologies for any confusion in my previous response. Upon further consideration,
the Suzuki GSX-S1000 may not be the best option for a beginner due to its high
power and aggressive handling characteristics.  Between the Kawasaki Z1000 and
the Suzuki GSX-S1000, the Z1000 might be a better option for a beginner as it
offers smoother power delivery and a more comfortable riding position.
Additionally, the Z1000 is known for its versatility and is easier to manage
than the more aggressive GSX-S1000 for riders with less experience.  However, as
a beginner, it would still be helpful to consider starting on a motorcycle with
less powerful capabilities to develop your riding skills first before moving on
to more powerful bikes like Z1000 or GSX-S1000.

[user]
i have a 250 cc with 33 hp motorcycle and im good with it

[assistant]
That's great! Your experience with a 250cc motorcycle will definitely be helpful
as you consider moving on to bigger bikes. Given your experience, moving up to a
Kawasaki Z1000 might be manageable for you. Although the Z1000 has more power,
it is still easier to manage compared to the Suzuki GSX-S1000.  It is essential
to make a gradual transition and always prioritize safety while familiarizing
yourself with the handling and power of a larger motorcycle like the Z1000. Test
riding the motorcycle, if possible, would help you make an informed decision
about whether or not it's the right choice for your riding experience and
skills.
------------------------------------------------------------
--- conversation_id: 8a7b08d84d6a24df1379e76142efe429 | intent_major: commercial_investigation ---
[user]
Top 7 T-shirt Printing Companies in the UK

[assistant]
1. Printsome - Printsome is one of the leading T-shirt printing companies in the
UK, focusing on delivering high-quality custom printing services for both
individuals and businesses.  2. Spreadshirt - Spreadshirt is a popular T-shirt
printing company that helps individuals and businesses design and print custom
T-shirts, hoodies, and other apparel.  3. Camaloon - Camaloon offers a range of
customisable products, including T-shirts, bags, stickers, and buttons.  4.
Rapanui Clothing - Rapanui Clothing specialises in ethically sourced and
sustainable T-shirt printing, creating eye-catching designs that both look great
and do good.  5. Banana Moon - Banana Moon is a T-shirt printing company that
offers a huge range of clothing, from hoodies and jackets to T-shirts and polos.
6. Urban T-shirts - Urban T-shirts produces high-quality custom T-shirts and
other apparel, with a range of printing options including screen printing,
embroidery, and vinyl heat transfer.  7. Tee Junction - Tee Junction is a
T-shirt printing company that specialises in producing high-quality custom
T-shirts for businesses, social events, and personal use. Their goal is to make
the process of designing and printing T-shirts as simple and stress-free as
possible.

[user]
Write a SEO-freindly article of 1200 words for Top 7 T-shirt Printing Companies
in the UK Kindly ensure that the keywords- Spain, Belgium, France, the UK, and
the Netherlands are included in the text. Create SEO-friendly content by
incorporating strategically placed keywords within H1 to H4 tags that fulfill
SEO requirements. Additionally, craft an SEO-friendly meta title and meta
description to increase your website's ranking.

[assistant]
Meta Title: Top 7 T-shirt Printing Companies in the UK | Custom T-shirt Printing
Services  Meta Description: Looking for high-quality custom T-shirt printing
services in the UK? Check out our list of the top 7 T-shirt printing companies,
including Printsome, Spreadshirt, and Camaloon.  If you're looking for high-
quality custom T-shirt printing services in the UK, you're in luck. With a range
of printing options and a variety of designs to choose from, there has never
been a better time to get your hands on a custom T-shirt that speaks to your
unique personality and style.  To help you get started, we've put together a
list of the top 7 T-shirt printing companies in the UK. Whether you're an
individual looking for a one-of-a-kind T-shirt design, or a business in need of
custom shirts for your staff, these companies are sure to meet your needs.  1.
Printsome  Printsome is one of the leading T-shirt printing companies in the UK,
offering high-quality custom printing services for both individuals and
businesses. With offices in Spain, Belgium, France, the UK, and the Netherlands,
Printsome prides itself on its flexibility and commitment to customer
satisfaction. From screen printing to DTG printing, this company uses the latest
printing technologies to deliver outstanding results every time.  2. Spreadshirt
Spreadshirt is a popular T-shirt printing company that helps individuals and
businesses design and print custom T-shirts, hoodies, and other apparel. With
headquarters in Germany and a strong presence in the UK, France, and the
Netherlands, Spreadshirt has a wealth of experience in creating unique designs
and providing top-notch printing services. Whether you need a single shirt or a
bulk order, this company is sure to exceed your expectations.  3. Camaloon
Camaloon is another major player in the T-shirt printing industry, offering a
range of customisable products, including T-shirts, bags, stickers, and buttons.
With offices in Spain and France, Camaloon combines cutting-edge printing
technologies with high-quality materials to create eye-catching designs that are
sure to stand out. Whether you're looking for a classic cotton T-shirt or a
stylish hoodie, Camaloon has you covered.  4. Rapanui Clothing  If you're
looking for sustainable and ethical T-shirt printing services, Rapanui Clothing
is the company for you. With a strong focus on environmental responsibility and
social justice, Rapanui Clothing sources its materials from sustainable sources
and uses eco-friendly printing methods to create stunning designs. Based in the
UK, this company has a range of T-shirts, hoodies, and other apparel that are
sure to make a statement.  5. Banana Moon  Banana Moon is a T-shirt printing
company that offers a huge range of clothing, from hoodies and jackets to
T-shirts and polos. With offices in France and the UK, Banana Moon has a wealth
of experience in printing on a variety of materials and producing high-quality
designs. Whether you need a custom shirt for your business or a unique design
for a personal event, Banana Moon has the expertise and resources to get the job
done.  6. Urban T-shirts  Urban T-shirts is a UK-based T-shirt printing company
that specialises in producing high-quality custom T-shirts and other apparel.
With a range of printing options including screen printing, embroidery, and
vinyl heat transfer, this company can produce a variety of designs to meet your
needs. Whether you're looking for a bold graphic or a simple logo, Urban
T-shirts has the expertise to bring your vision to life.  7. Tee Junction  Tee
Junction is a T-shirt printing company that specialises in producing high-
quality custom T-shirts for businesses, social events, and personal use. With a
wide range of materials and printing options, Tee Junction can customise your
T-shirt design to your exact specifications. Based in the UK, Tee Junction
prides itself on its attention to detail and commitment to customer
satisfaction.  In conclusion, if you're looking for T-shirt printing services in
the UK, there are plenty of great options available. From sustainable and
ethical brands like Rapanui Clothing to major players like Spreadshirt and
Printsome, these companies offer top-notch printing services and a variety of
design options to meet your needs. So why not get started on designing your own
custom T-shirt today?
------------------------------------------------------------

============================================================
intent_revised: informational (showing 3 of 1939)
============================================================
--- conversation_id: 73a7b381458ceeee63872eeb23769459 | intent_major: commercial_investigation ---
[user]
model = Sequential() model.add(LSTM(64, input_shape=(lookback, 7)))
model.add(Dense(32, activation='relu')) model.add(Dense(7,
activation='sigmoid')) model.compile(loss='mean_squared_error',
optimizer='adam')  #训练模型 model.fit(train_X, train_Y, batch_size=batch_size,
epochs=epochs, validation_data=(test_X, test_Y))  #预测下一期双色球 last_data =
data[['red1', 'red2', 'red3', 'red4', 'red5', 'red6', 'blue']].tail(lookback)
last_data = (last_data - 1) / np.array([33, 33, 33, 33, 33, 33, 16]) last_data =
np.array(last_data) last_data = np.reshape(last_data, (1, lookback, 7))
prediction = model.predict(last_data) prediction = np.round(prediction *
np.array([33, 33, 33, 33, 33, 33, 16]) + np.array([1, 1, 1, 1, 1, 1, 1]))
逐行解释上面的代码

[assistant]
1. 创建一个Sequential模型（线性堆栈模型）。 ```python model = Sequential() ```  2.
向模型中添加一个LSTM（Long Short-Term Memory，长短时记忆）层，64个单元，输入数据形状为(lookback, 7)。
```python model.add(LSTM(64, input_shape=(lookback, 7))) ```  3.
向模型中添加一个全连接层（Dense），32个神经元，使用ReLU（Rectified Linear Unit，修正线性单元）作为激活函数。 ```python
model.add(Dense(32, activation='relu')) ```  4.
向模型中添加一个输出层，7个神经元，使用Sigmoid（S型激活函数）作为激活函数。 ```python model.add(Dense(7,
activation='sigmoid')) ```  5. 编译模型，使用均方误差损失函数（mean_squared_error）和Adam优化器。
```python model.compile(loss='mean_squared_error', optimizer='adam') ```  6.
训练模型，使用训练数据（train_X,
train_Y），损失函数优化后的优化器，批量大小（batch_size），训练次数（epochs），并验证模型效果（test_X, test_Y）。
```python model.fit(train_X, train_Y, batch_size=batch_size, epochs=epochs,
validation_data=(test_X, test_Y)) ```  7. 获取数据的最后lookback期数据，用于预测下一期双色球。
```python last_data = data[['red1', 'red2', 'red3', 'red4', 'red5', 'red6',
'blue']].tail(lookback) ```  8. 对数据进行归一化处理，将红球除以33，蓝球除以16，然后减去1。 ```python
last_data = (last_data - 1) / np.array([33, 33, 33, 33, 33, 33, 16]) ```  9.
转换数据格式为NumPy数组并重塑为(1, lookback, 7)的形状，以适应模型的输入格式。 ```python last_data =
np.array(last_data) last_data = np.reshape(last_data, (1, lookback, 7)) ```  10.
使用训练好的模型对最后一期数据进行预测，得到下期双色球的预测值。 ```python prediction = model.predict(last_data)
```  11. 将预测值从归一化的范围恢复到实际的双色球范围，并对预测结果进行取整。 ```python prediction =
np.round(prediction * np.array([33, 33, 33, 33, 33, 33, 16]) + np.array([1, 1,
1, 1, 1, 1, 1])) ```
------------------------------------------------------------
--- conversation_id: c24c8431418005ccd2c4c6d9d1247cdc | intent_major: commercial_investigation ---
[user]
Case Project 12-8: Biometric Laws  Several states now have biometric laws, and
others are considering similar legislation. Research these laws that are
currently in place from three states. Compare the laws. Are they sufficient?
What are their weaknesses? Finally, create your own law that you believe would
protect the biometric data of users. Write a one-page paper on your research.

[assistant]
Title: Biometric Laws: A Comparative Analysis and Proposal for Effective Data
Protection  Introduction: Biometric laws have emerged as an essential framework
to address the growing concerns regarding the collection and protection of
individuals' biometric data. This paper aims to explore the existing biometric
laws in three different states, assess their effectiveness, identify their
weaknesses, and propose an improved legislative framework for biometric data
protection.  Comparison of Biometric Laws: 1. State A - Biometric Information
Privacy Act (BIPA)    - BIPA requires companies to obtain informed written
consent before collecting biometric information.    - It prohibits the sale or
profit gain through biometric data.    - BIPA also mandates companies to develop
guidelines for the secure storage and disposal of collected biometric
information.  2. State B - Biometric Privacy Act (BPA)    - BPA requires
companies to inform individuals about the purpose and duration of biometric data
collection.    - It prohibits the disclosure of biometric information without
obtaining explicit consent from the concerned individual.    - BPA provides a
private right of action, allowing individuals to sue for damages in case of data
breaches or unauthorized use of biometric data.  3. State C - Biometric
Identifiers Information Privacy Act (BIIPA)    - BIIPA mandates obtaining
written consent from individuals before collecting biometric identifiers.    -
It requires organizations to establish publicly available retention schedules
for biometric identifiers.    - BIIPA also prohibits the sale, lease, or
disclosure of biometric identifiers without consent.  Assessment of Existing
Laws: Although the existing biometric laws in these states are progressive in
terms of addressing the potential risks associated with biometric data
collection, they do possess certain weaknesses. Some common weaknesses include:
1. Lack of Uniformity: Each state has its own set of biometric laws, resulting
in a lack of consistency and standardization between jurisdictions. This can
lead to confusion for businesses operating in multiple states.  2. Limited
Scope: Existing laws primarily focus on the private sector and fail to
adequately cover government entities engaged in biometric data collection.  3.
Ambiguous Definitions: Certain terms such as "informed written consent" and
"secure storage" lack detailed definitions, leaving room for interpretation and
potential loopholes.  Proposal for an Enhanced Biometric Law: To address the
weaknesses and maximize the protection of biometric data, an ideal biometric law
should possess the following features:  1. National Legislation: A comprehensive
federal law should be established to promote uniformity and clarity across all
jurisdictions.  2. Scope Expansion: The law should encompass both private and
public sector entities engaged in biometric data collection to ensure
comprehensive coverage.  3. Strict Consent Requirements: The legislation should
mandate obtaining explicit, informed, and written consent from individuals prior
to collecting their biometric data.  4. Enhanced Security Measures: Clear
guidelines should be provided for secure storage, encryption, and disposal of
biometric data to minimize the risk of unauthorized access.  5. Penalties and
Liability: Establishing significant punitive measures, including strict fines
and penalties for non-compliance or data breaches, would deter entities from
mishandling biometric data.  Conclusion: While the existing biometric laws in

## Embedding-based vertical

Embed **all_queries + all_answers** and assign the reference vertical with highest cosine similarity.

In [7]:
if RUN_EMBEDDING_VERTICAL:
    from commercial_vertical_utils import assign_vertical_embedding

    df = assign_vertical_embedding(
        df,
        text_col_queries="all_queries",
        text_col_answers="all_answers",
    )
    print("Vertical (embedding) value counts:")
    display(df["vertical_embedding"].value_counts().head(15))

/Users/Larry.Jin/miniconda3/envs/wildchat/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2530.23it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2292.71it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Vertical (embedding) value counts:

vertical_embedding
Health          375
Other           289
Technology      263
Sports          173
Shopping        166
Travel          163
Education       162
Food & Drink    137
Finance         115
Automotive       92
Real Estate      65
Name: count, dtype: int64

## Rule-based vertical (optional)

Assign vertical from curated keyword rules (first match wins) over **all_queries + all_answers**.

In [8]:
if RUN_RULE_VERTICAL:
    from commercial_vertical_utils import assign_vertical_rule_based

    df = assign_vertical_rule_based(
        df,
        text_col_queries="all_queries",
        text_col_answers="all_answers",
    )
    print("Vertical (rule) value counts:")
    display(df["vertical_rule"].value_counts().head(15))

Vertical (rule) value counts:

vertical_rule
Sports          846
Real Estate     420
Technology      301
Health          213
Other            64
Shopping         52
Automotive       50
Education        23
Travel           17
Finance          12
Food & Drink      2
Name: count, dtype: int64

## Summary: counts and agreement

Compare vertical distributions across methods and intent_revised vs intent_major.

In [9]:
summary_cols = ["vertical_tier1_iab", "vertical_tier1_llm", "vertical_embedding", "vertical_rule"]
existing = [c for c in summary_cols if c in df.columns]
if existing:
    for col in existing:
        print(f"--- {col} ---")
        display(df[col].value_counts().head(10))
if "intent_revised" in df.columns:
    print("Intent revised vs intent_major (crosstab):")
    display(pd.crosstab(df["intent_major"], df["intent_revised"], normalize="index").round(2))

--- vertical_tier1_iab ---

vertical_tier1_iab
Family and Relationships               684
Personal Celebrations & Life Events    277
Style & Fashion                        161
Sensitive Topics                       149
Home & Garden                          104
Hobbies & Interests                    103
Real Estate                             98
Food & Drink                            93
Sports                                  61
Healthy Living                          48
Name: count, dtype: int64

--- vertical_tier1_llm ---

vertical_tier1_llm
Other           792
Technology      327
Education       323
Health          275
Sports           97
Travel           40
Shopping         34
Finance          34
Food & Drink     34
Automotive       11
Name: count, dtype: int64

--- vertical_embedding ---

vertical_embedding
Health          375
Other           289
Technology      263
Sports          173
Shopping        166
Travel          163
Education       162
Food & Drink    137
Finance         115
Automotive       92
Name: count, dtype: int64

--- vertical_rule ---

vertical_rule
Sports         846
Real Estate    420
Technology     301
Health         213
Other           64
Shopping        52
Automotive      50
Education       23
Travel          17
Finance         12
Name: count, dtype: int64

Intent revised vs intent_major (crosstab):

intent_revised,commercial_investigation,informational,navigational,transactional
intent_major,,,,
commercial_investigation,0.02,0.97,0.0,0.0